---
jobs:
- name: job-deploy-app
  public: true
  serial: true
  plan:
  - get: resource-cf-app
    trigger: true
  - put: resource-deploy-cf-app
    params:
      manifest: resource-cf-app/manifest.yml
      path: resource-cf-app

- name: job-scale-app
  public: true
  serial: true
  plan:
  - get: resource-cf-app
    trigger: true
    # make sure this job only gets to run after the previous job passed
    
  - task: scale-cf-app
    config:
      # Hints: How to configure a task, see the following link
      # https://concourse.ci/running-tasks.html#configuring-tasks
      # More specificly, you need to configue: platform, image,inputs and run
      # the script you run is in `cf-env/bin/scale-app`,it will help you configure
      # the task correctly
      # most of the args/varibles you need are already in credentials.yml
  
resources:
- name: resource-cf-app
  type: git
  source:
    uri: https://github.com/xiujiao/cf-env

- name: resource-deploy-cf-app
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true
