---
# Reminder: In YAML files, spaces and tabs matter!
jobs:
- name: job-deploy-app
  public: true
  serial: true
  plan:
  - get: resource-cf-app
    # Configure the trigger to be true, so pushing your changes to your
    # repo will trigger the pipeline.
    # Hints:
    #   1) You will find useful info here:
    #      `https://github.com/concourse/cf-resource`

  - put: resource-deploy-cf-app
    params:
      # Configure the parameters you need to deploy the app to cf
      # Hints:
      #   1) You will find useful info here:
      #      `https://github.com/concourse/cf-resource`

resources:
# Configure your resources.
- name: resource-cf-app
  # Configure your cf app resource,
  # Hints:
  #   1) This one is of type `git` and should be fetched from
  #      the cf-env repo you forked to your own github account.
  #   2) For information on configuring a git resource refer to
  #      `https://github.com/concourse/git-resource`
  type:
  source:

- name: resource-deploy-cf-app
  # Configure a resource for deploying your CF app
  # Hints:
  #   1) The type is cf;
  #   2) You can refer to `https://github.com/concourse/cf-resource`;
  #   3) Instead of directly showng username and password etc.,
  #      instead use variables in `credentials.yml`;
  #   4) Set `skip_cert_check` to be true for this example.
