---
jobs:
  # Reminder: In yml files, space and tabs matters
- name: job-deploy-app
  public: true
  serial: true
  plan:
  - get: resource-cf-app
    # configure the trigger to be true, so it will trigger the pipeline
    # when you push your changes to the repo after you already set up the pipeline. 

  - put: resource-deploy-cf-app
    params:
      # Configure the parameters you need to deploy the app to cf
      # You will find useful info here: `https://github.com/concourse/cf-resource` 

resources:
- name: resource-cf-app
  # configure your resources, hints: it is a git type, and it should be fetched from
  # the cf-env repo you forked to your own github account. About how to configure
  # git type resource, you can refer: `https://github.com/concourse/git-resource`
  type: 
  source:
    

- name: resource-deploy-cf-app
  # configure your resources: hints: 1) the type is cf; 2) you can refer 
  # `https://github.com/concourse/cf-resource`; 3) instead of directly 
  # show username and password etc., suggesting you use the variables 
  # setting in `credentials.yml`; 4) suggesting that we set 
  # `skip_cert_check` to be true in this example.
 
